# Generated by Django 4.2.5 on 2023-10-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=510)),
                ('city', models.CharField(max_length=2651)),
                ('country', models.CharField(max_length=250)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
